[package]
name = "telnet-animations"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.19", features = ["full"] }
toml = { version = "0.5" }
