[package]
name = "telnet-animations"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.27", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
toml = { version = "0.7" }
